"""Tests for E-229-08: defensive positioning bundle assembler.

Covers AC-1 through AC-8:
* AC-1: 4-page assembly order + content per page; writes to
  `data/reports/{slug}/index.html`
* AC-2: 2 landscape + 1 portrait named @page directives
* AC-3: bundle generated by `generate_report(public_id)` per the
  existing pattern (E-228 lifecycle preserved)
* AC-4 + AC-4a: consistent coverage cue across pages + snapshot
  persistence via `bundle_snapshot.json` sidecar (re-render reads
  snapshot, ignores live DB freshness)
* AC-5: zero-coverage degradation still produces 4 pages
* AC-6 (a-e): cross-AC smoke tests + AC-6(e) re-render persistence
* AC-7: LLM render-time threading per flagged batter
* AC-8: LLM ephemerality — no INSERT/UPDATE against positioning tables
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path
from unittest.mock import patch

import pytest

import src.reports.positioning_bundle as positioning_bundle
from src.reports.positioning import COVERED_POSITIONS
from src.reports.positioning_bundle import generate_positioning_bundle
from tests.conftest import load_real_schema


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


_SEASON = "2026-spring-hs"


@pytest.fixture()
def conn(tmp_path):
    """In-memory schema-loaded connection seeded with a tracked opponent
    + member team + season row."""
    path = tmp_path / "test.db"
    c = sqlite3.connect(str(path))
    c.row_factory = sqlite3.Row
    load_real_schema(c)
    c.execute(
        "INSERT INTO teams (id, name, public_id, season_year, membership_type) "
        "VALUES (1, 'Opp Bears', 'opp-bears', 2026, 'tracked')"
    )
    c.execute(
        "INSERT INTO teams (id, name, membership_type) "
        "VALUES (99, 'LSB Varsity', 'member')"
    )
    c.execute(
        "INSERT INTO seasons (season_id, name, season_type, year) "
        "VALUES ('2026-spring-hs', '2026', 'spring-hs', 2026)"
    )
    c.commit()
    yield c
    c.close()


def _seed_player(conn, player_id, first, last):
    conn.execute(
        "INSERT OR IGNORE INTO players (player_id, first_name, last_name) "
        "VALUES (?, ?, ?)",
        (player_id, first, last),
    )


def _seed_roster(conn, player_id, jersey, team_id=1, season_id=_SEASON):
    if jersey is not None:
        conn.execute(
            "INSERT OR IGNORE INTO team_rosters "
            "(team_id, player_id, season_id, jersey_number) "
            "VALUES (?, ?, ?, ?)",
            (team_id, player_id, season_id, jersey),
        )


def _seed_aggregates(conn, *, bip_count=60, is_low_confidence=0,
                     team_id=1, season_id=_SEASON, perspective_team_id=1):
    for p in COVERED_POSITIONS:
        conn.execute(
            """
            INSERT INTO team_position_aggregate (
                team_id, season_id, perspective_team_id, position,
                star_x, star_y, bip_count, is_low_confidence
            ) VALUES (?, ?, ?, ?, 160.0, 200.0, ?, ?)
            """,
            (team_id, season_id, perspective_team_id, p,
             bip_count, is_low_confidence),
        )


def _seed_batter_row(conn, *, player_id, position,
                    zone_id=None, is_thin=0, bip_count=20,
                    direction_deviation=0, depth_deviation=0,
                    team_id=1, season_id=_SEASON, perspective_team_id=1):
    conn.execute(
        """
        INSERT INTO batter_positioning (
            player_id, team_id, season_id, perspective_team_id, position,
            direction_deviation, depth_deviation, zone_id,
            is_thin, bip_count, hr_count
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
        """,
        (player_id, team_id, season_id, perspective_team_id, position,
         direction_deviation, depth_deviation, zone_id, is_thin, bip_count),
    )


def _seed_full_opponent(conn):
    """Three batters across the 6 covered positions:
       p1 (Ramirez, #7)  -- flagged at LF (zone A)
       p2 (Davis, #11)   -- flagged at LF (zone B) and RF (zone H)
       p3 (Aaron, #3)    -- all default
    """
    _seed_aggregates(conn)
    _seed_player(conn, "p1", "Hank", "Ramirez")
    _seed_roster(conn, "p1", "7")
    _seed_batter_row(conn, player_id="p1", position="LF",
                     zone_id="A", direction_deviation=-1, depth_deviation=-1)
    for p in ("CF", "RF", "3B", "SS", "2B"):
        _seed_batter_row(conn, player_id="p1", position=p)

    _seed_player(conn, "p2", "Marcus", "Davis")
    _seed_roster(conn, "p2", "11")
    _seed_batter_row(conn, player_id="p2", position="LF",
                     zone_id="B", direction_deviation=-1)
    _seed_batter_row(conn, player_id="p2", position="RF",
                     zone_id="H", direction_deviation=1, depth_deviation=1)
    for p in ("CF", "3B", "SS", "2B"):
        _seed_batter_row(conn, player_id="p2", position=p)

    _seed_player(conn, "p3", "Tony", "Aaron")
    _seed_roster(conn, "p3", "3")
    for p in COVERED_POSITIONS:
        _seed_batter_row(conn, player_id="p3", position=p)
    conn.commit()


# ---------------------------------------------------------------------------
# AC-1 / AC-6 (a, b) -- 4-page assembly + content per page
# ---------------------------------------------------------------------------


class TestBundleAssembly:
    def test_returns_html_string(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        assert isinstance(html, str)
        assert html.startswith("<!DOCTYPE html>")
        assert "</html>" in html

    def test_includes_call_sheet_section(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        # Call sheet section has the .positioning-call-sheet wrapper class
        # AND the matrix table from positioning_call_sheet.html.
        assert "positioning-call-sheet" in html
        assert "positioning-call-sheet-table" in html

    def test_includes_prep_page_section(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        # Prep page section has the .positioning-prep wrapper.
        assert "positioning-prep-page" in html

    def test_includes_cards_section(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        # Cards section has the .positioning-cards-sheet wrapper.
        assert "positioning-cards-sheet" in html

    def test_section_order_is_call_sheet_then_prep_then_cards(self, conn):
        """AC-1 page-order assertion: the partials appear in document
        order in the rendered HTML."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        idx_call = html.find("positioning-call-sheet")
        idx_prep = html.find("positioning-prep-page")
        idx_cards = html.find("positioning-cards-sheet")
        assert idx_call > 0
        assert idx_prep > 0
        assert idx_cards > 0
        assert idx_call < idx_prep < idx_cards

    def test_page_4_slots_3_and_4_are_compass_key_and_opponent_context(
        self, conn,
    ):
        """AC-1 page-4 slot fill: compass-key + opponent-context-card per
        E-229-05 AC-9 + UXD I-2 lock. We verify the template carries the
        slot identifiers in the rendered HTML."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12",
            game_count=12,
        )
        # The cards template has two sheets; sheet 2 carries slot 3-4
        # markers via CSS class identifiers (compass-key + opponent-
        # context-card per E-229-05). We check structural identifiers
        # in the rendered HTML.
        assert "compass-key" in html or "compass_key" in html
        assert "opponent-context" in html or "opponent_context" in html


# ---------------------------------------------------------------------------
# AC-2 / AC-6 (a) -- Print CSS uses two landscape + one portrait @page
# ---------------------------------------------------------------------------


class TestPrintCSS:
    def test_call_sheet_page_directive_landscape(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        m = re.search(
            r"@page\s+call-sheet\s*\{[^}]*size:\s*letter\s+landscape",
            html, re.IGNORECASE | re.DOTALL,
        )
        assert m is not None, "missing @page call-sheet { ... letter landscape ... }"

    def test_prep_page_page_directive_landscape(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        m = re.search(
            r"@page\s+prep-page\s*\{[^}]*size:\s*letter\s+landscape",
            html, re.IGNORECASE | re.DOTALL,
        )
        assert m is not None, "missing @page prep-page { ... letter landscape ... }"

    def test_cards_page_directive_portrait(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        m = re.search(
            r"@page\s+positioning-cards\s*\{[^}]*size:\s*letter\s+portrait",
            html, re.IGNORECASE | re.DOTALL,
        )
        assert m is not None, "missing @page positioning-cards { ... letter portrait ... }"

    def test_cards_page_margin_zero(self, conn):
        """F1 (codex P1): the @page positioning-cards rule MUST use
        `margin: 0` per locked-constants artifact §A "Print page margin:
        0 in (all four sides)". With any positive margin the 2x2 grid
        (4.25"x5.5" cards = 8.5"x11" total) overflows the printable
        area and browsers clip the right + bottom edges."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        block = re.search(
            r"@page\s+positioning-cards\s*\{([^}]*)\}",
            html, re.IGNORECASE | re.DOTALL,
        )
        assert block is not None, "missing @page positioning-cards block"
        body = block.group(1)
        margin_m = re.search(r"margin\s*:\s*([^;]+);", body, re.IGNORECASE)
        assert margin_m is not None, "@page positioning-cards must declare a margin"
        margin_value = margin_m.group(1).strip()
        assert margin_value == "0", (
            f"@page positioning-cards margin must be `0` (not `{margin_value}`) "
            f"per locked-constants artifact §A -- positive margins cause the "
            f"2x2 grid to overflow the printable area."
        )

    def test_exactly_three_distinct_page_blocks(self, conn):
        """AC-2: two landscape (call-sheet + prep-page) + one portrait
        (positioning-cards) = three distinct named @page blocks."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Each @page rule looks like: @page <name> { ... }
        page_block_names = re.findall(
            r"@page\s+([a-z-]+)\s*\{", html, re.IGNORECASE,
        )
        assert set(page_block_names) == {
            "call-sheet", "prep-page", "positioning-cards",
        }


# ---------------------------------------------------------------------------
# AC-4 / AC-4a / AC-6 (d, e) -- Coverage-cue consistency + snapshot
# ---------------------------------------------------------------------------


class TestCoverageCue:
    def test_coverage_cue_consistent_across_pages(self, conn):
        """AC-4: all four pages cite the same coverage cue. The string
        `Through Apr 12 (12 games)` should appear at least 3 times
        (once per page that has a header — page 4 inherits via cards
        template's coverage_cue context)."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        cue = "Through Apr 12 (12 games)"
        # The cue should appear at minimum: call-sheet header, prep
        # header, and at least one card header on each portrait sheet.
        count = html.count(cue)
        assert count >= 3, (
            f"coverage cue should appear on at least 3 pages; "
            f"found {count} occurrences of {cue!r}"
        )

    def test_coverage_cue_snapshot_in_html(self, conn):
        """AC-4a: the cue captured at generation time is embedded in the
        rendered HTML so re-viewing the bundle from disk shows the same
        cue (no live-data recomputation). We assert the cue is present
        as a literal string — the storage shape (per AC-4a) is "JSON
        field in the bundle's template context that the HTML renders
        directly"."""
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        assert "Through Apr 12 (12 games)" in html

    def test_coverage_cue_unchanged_when_db_updated(self, conn, tmp_path):
        """AC-4a + AC-6 (e): re-render from disk must show the same cue
        even if the underlying DB receives new games after generation.

        Strategy: render once with through_date='Apr 12' / game_count=12.
        Save the HTML. Then re-render with the same kwargs but after
        updating aggregate bip_counts in the DB to simulate later
        scouting. The second render with the SAME kwargs MUST produce
        the same cue. (We can't read back from disk to test this
        without the pipeline-wiring layer; the equivalent semantic
        guarantee is that the cue is a pure function of the caller-
        supplied kwargs, not of the DB.)"""
        _seed_full_opponent(conn)
        html_v1 = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Mutate DB: add new aggregate bip rows to mimic later scouting.
        for p in COVERED_POSITIONS:
            conn.execute(
                "UPDATE team_position_aggregate SET bip_count = 200 "
                "WHERE position = ? AND team_id = 1",
                (p,),
            )
        conn.commit()
        # Re-render with the SNAPSHOT kwargs from the prior generation.
        html_v2 = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Both renders must show the same cue (snapshot survives).
        cue = "Through Apr 12 (12 games)"
        assert cue in html_v1
        assert cue in html_v2


# ---------------------------------------------------------------------------
# AC-5 / AC-6 (c) -- Zero-coverage degradation
# ---------------------------------------------------------------------------


class TestZeroCoverage:
    def test_zero_bip_team_still_produces_all_four_pages(self, conn):
        """AC-5: when team has 0 BIPs total, the bundle still produces
        all four pages — none of the sections is silently dropped."""
        # No aggregates seeded (zero coverage everywhere).
        _seed_player(conn, "p1", "Hank", "Ramirez")
        _seed_roster(conn, "p1", "7")
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # All three section wrappers still appear.
        assert "positioning-call-sheet" in html
        assert "positioning-prep-page" in html
        assert "positioning-cards-sheet" in html

    def test_zero_bip_renders_zero_coverage_message(self, conn):
        """AC-5: call sheet + prep page render the zero-coverage
        variant in place of the matrix / field."""
        _seed_player(conn, "p1", "Hank", "Ramirez")
        _seed_roster(conn, "p1", "7")
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        assert "Not enough spray data" in html

    def test_low_bip_team_below_15_threshold_renders_zero_coverage(self, conn):
        """AC-5: when team aggregate bip_count < 15 the call sheet +
        prep page still degrade to zero-coverage. (Cards use the same
        15-BIP threshold per E-229-03 AC-9.)"""
        _seed_aggregates(conn, bip_count=10)
        _seed_player(conn, "p1", "Hank", "Ramirez")
        _seed_roster(conn, "p1", "7")
        for p in COVERED_POSITIONS:
            _seed_batter_row(
                conn, player_id="p1", position=p, bip_count=10,
            )
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        assert "positioning-call-sheet" in html
        assert "positioning-prep-page" in html
        assert "positioning-cards-sheet" in html


# ---------------------------------------------------------------------------
# AC-7 -- LLM render-time threading
# ---------------------------------------------------------------------------


class TestLLMRenderTimeThreading:
    def test_llm_unavailable_skips_rationales_silently(self, conn, monkeypatch):
        """AC-7: when is_llm_available() returns False, the bundle
        renders without rationale lines for any batter, INFO log only."""
        _seed_full_opponent(conn)
        # Strip OPENROUTER_API_KEY so is_llm_available() returns False.
        monkeypatch.delenv("OPENROUTER_API_KEY", raising=False)

        with patch(
            "src.reports.positioning_bundle.generate_rationale"
        ) as mock_gen:
            html = generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        # The shortcut in _build_rationales bails before any
        # generate_rationale call when is_llm_available is False.
        mock_gen.assert_not_called()
        # Bundle still produced, no crash.
        assert "positioning-call-sheet" in html

    def test_llm_available_calls_generate_rationale_per_flagged_batter(
        self, conn, monkeypatch,
    ):
        """AC-7: for each flagged batter the assembler calls
        `generate_rationale(batter_row, aggregate_row, batter_metadata)`."""
        _seed_full_opponent(conn)
        # p1 + p2 are flagged (3 flagged (player, position) rows across
        # them: p1@LF, p2@LF, p2@RF). The assembler dedup's by player_id
        # — so the call count should be 2.
        monkeypatch.setenv("OPENROUTER_API_KEY", "sk-test")

        with patch(
            "src.reports.positioning_bundle.generate_rationale",
            return_value=None,
        ) as mock_gen:
            html = generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        assert mock_gen.call_count == 2  # p1 + p2 (deduped by player_id)
        assert "positioning-call-sheet" in html

    def test_llm_rationale_threaded_into_call_sheet_note(
        self, conn, monkeypatch,
    ):
        """AC-7: a rationale returned by the LLM appears in the
        rendered call-sheet NOTE cell for the flagged batter."""
        _seed_full_opponent(conn)
        monkeypatch.setenv("OPENROUTER_API_KEY", "sk-test")

        # Return distinct rationales per player so we can verify
        # threading.
        def fake_rationale(batter_row, aggregate_row, batter_metadata):
            if batter_metadata["last_name"] == "Ramirez":
                return "Ramirez prefers Zone A on inside fastballs early counts."
            if batter_metadata["last_name"] == "Davis":
                return "Davis pulls 11 grounders to Zone B against breaking pitches."
            return None

        with patch(
            "src.reports.positioning_bundle.generate_rationale",
            side_effect=fake_rationale,
        ):
            html = generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        # Both rationales appear in the rendered HTML.
        assert "Ramirez prefers Zone A on inside fastballs early counts." in html
        assert "Davis pulls 11 grounders to Zone B against breaking pitches." in html

    def test_llm_exception_is_non_fatal(self, conn, monkeypatch):
        """AC-7: an exception raised by generate_rationale mid-call is
        caught at the per-batter level; bundle still renders for the
        rest of the lineup."""
        _seed_full_opponent(conn)
        monkeypatch.setenv("OPENROUTER_API_KEY", "sk-test")

        with patch(
            "src.reports.positioning_bundle.generate_rationale",
            side_effect=RuntimeError("synthetic LLM crash"),
        ):
            html = generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        # Bundle still produced; no rationale text in it.
        assert "positioning-call-sheet" in html

    def test_llm_returns_none_for_one_batter_others_still_render(
        self, conn, monkeypatch,
    ):
        """AC-7: a per-batter None return drops the rationale for that
        batter but the others' rationales still appear."""
        _seed_full_opponent(conn)
        monkeypatch.setenv("OPENROUTER_API_KEY", "sk-test")

        def fake_rationale(batter_row, aggregate_row, batter_metadata):
            if batter_metadata["last_name"] == "Ramirez":
                return None  # validation rejection
            return "Davis has 11 left-side pulled balls this season clearly."

        with patch(
            "src.reports.positioning_bundle.generate_rationale",
            side_effect=fake_rationale,
        ):
            html = generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        # Davis's rationale is in the HTML; Ramirez's is dropped.
        assert "Davis has 11 left-side pulled balls" in html


# ---------------------------------------------------------------------------
# AC-8 -- LLM ephemerality (no DB writes)
# ---------------------------------------------------------------------------


class TestLLMEphemerality:
    """AC-8: a test asserts no INSERT/UPDATE statements are issued
    against `batter_positioning` or `team_position_aggregate` during
    the LLM rationale path."""

    SOURCE_PATH = Path(positioning_bundle.__file__)

    def test_module_source_has_no_insert_or_update_on_positioning_tables(
        self,
    ):
        """Grep AC: the assembler module emits zero INSERT/UPDATE
        statements against positioning tables. (SELECT is fine — the
        assembler reads to build context.)"""
        text = self.SOURCE_PATH.read_text()
        forbidden_patterns = (
            r"INSERT\s+INTO\s+batter_positioning",
            r"UPDATE\s+batter_positioning",
            r"INSERT\s+INTO\s+team_position_aggregate",
            r"UPDATE\s+team_position_aggregate",
        )
        for pat in forbidden_patterns:
            assert not re.search(pat, text, re.IGNORECASE), (
                f"positioning_bundle.py must not write to positioning "
                f"tables (AC-8); found pattern {pat!r}"
            )

    def test_runtime_no_writes_during_llm_path(self, conn, monkeypatch):
        """Runtime AC-8: count INSERT/UPDATE statements against the
        positioning tables before and after a bundle render with the
        LLM enabled — the delta MUST be zero."""
        _seed_full_opponent(conn)
        monkeypatch.setenv("OPENROUTER_API_KEY", "sk-test")

        def count_rows():
            bp = conn.execute(
                "SELECT COUNT(*) FROM batter_positioning"
            ).fetchone()[0]
            agg = conn.execute(
                "SELECT COUNT(*) FROM team_position_aggregate"
            ).fetchone()[0]
            return bp, agg

        before = count_rows()
        with patch(
            "src.reports.positioning_bundle.generate_rationale",
            return_value=(
                "Pulls Zone B grounders early in counts against fastballs "
                "this season cleanly."
            ),
        ):
            generate_positioning_bundle(
                conn, "opp-bears", _SEASON,
                opponent_name="Opp Bears",
                through_date="Apr 12", game_count=12,
            )
        after = count_rows()
        assert after == before, (
            f"AC-8 violated: row counts changed during LLM path. "
            f"before={before} after={after}"
        )


# ---------------------------------------------------------------------------
# AC-3 -- function returns full HTML (lifecycle/wiring belongs to E-229-10)
# ---------------------------------------------------------------------------


class TestPublicAPI:
    def test_unknown_public_id_raises(self, conn):
        """The assembler is team-agnostic (AC-3) but must fail fast on
        unknown public_id rather than producing an empty bundle."""
        with pytest.raises(ValueError, match="No team found"):
            generate_positioning_bundle(
                conn, "no-such-team", _SEASON,
                opponent_name="Nothing",
                through_date="Apr 12", game_count=12,
            )

    def test_signature_returns_string(self, conn):
        _seed_full_opponent(conn)
        out = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        assert isinstance(out, str) and len(out) > 0


# ---------------------------------------------------------------------------
# R2: AC-1 / AC-3 / AC-4a / AC-6(e) -- bundle persistence + re-render
# ---------------------------------------------------------------------------
#
# The R1 deliverable shipped a standalone assembler function only. R2
# adds the integration into generate_report() via three helpers in
# generator.py:
#   * _write_positioning_bundle()   -- writes index.html + snapshot
#   * regenerate_positioning_bundle() -- re-renders from snapshot
#   * _format_through_date()         -- ISO date -> "Mon Day"
# Storage shape per AC-4a: file metadata sidecar at
# data/reports/{slug}/bundle_snapshot.json (option (b) of the three
# listed in AC-4a).


class _NoCloseConn:
    """Sqlite3-Connection proxy that no-ops .close() so test fixture
    lifetime is preserved across multiple generator-side get_connection()
    calls (each wrapped in `with closing(get_connection())`)."""

    def __init__(self, c):
        self._c = c

    def __getattr__(self, name):
        # Delegate everything (execute, executemany, commit, etc.) to
        # the underlying sqlite3.Connection.
        return getattr(self._c, name)

    def close(self):
        pass


class TestFormatThroughDate:
    def test_iso_date_formats_to_mon_day(self):
        from src.reports.generator import _format_through_date
        assert _format_through_date("2026-04-12") == "Apr 12"
        assert _format_through_date("2026-09-03") == "Sep 3"
        assert _format_through_date("2026-12-31") == "Dec 31"

    def test_none_or_empty_returns_empty(self):
        from src.reports.generator import _format_through_date
        assert _format_through_date(None) == ""
        assert _format_through_date("") == ""

    def test_unparseable_returns_empty(self):
        from src.reports.generator import _format_through_date
        assert _format_through_date("not-a-date") == ""


class TestBundlePersistence:
    """AC-1 + AC-3: bundle written to `data/reports/{slug}/index.html`;
    snapshot sidecar persisted alongside per AC-4a."""

    def test_write_creates_index_html_in_slug_dir(
        self, conn, tmp_path, monkeypatch,
    ):
        """AC-1: the bundle file ends up at the exact path
        `data/reports/{slug}/index.html`."""
        _seed_full_opponent(conn)
        import src.reports.generator as gen
        reports_dir = tmp_path / "data" / "reports"
        monkeypatch.setattr(gen, "_REPO_ROOT", tmp_path)
        monkeypatch.setattr(gen, "_REPORTS_DIR", reports_dir)
        monkeypatch.setattr(
            gen, "get_connection", lambda: _NoCloseConn(conn),
        )

        gen._write_positioning_bundle(
            slug="slug-abc",
            team_id=1,
            public_id="opp-bears",
            season_id=_SEASON,
            opponent_name="Opp Bears",
            freshness_date="2026-04-12",
            game_count=12,
        )
        bundle_path = reports_dir / "slug-abc" / "index.html"
        assert bundle_path.exists(), f"expected bundle at {bundle_path}"
        html = bundle_path.read_text(encoding="utf-8")
        assert "positioning-call-sheet" in html
        assert "Through Apr 12 (12 games)" in html

    def test_write_creates_bundle_snapshot_json(
        self, conn, tmp_path, monkeypatch,
    ):
        """AC-4a: the snapshot sidecar carries the coverage-cue inputs
        verbatim so re-renders reproduce the same cue."""
        _seed_full_opponent(conn)
        import src.reports.generator as gen
        reports_dir = tmp_path / "data" / "reports"
        monkeypatch.setattr(gen, "_REPO_ROOT", tmp_path)
        monkeypatch.setattr(gen, "_REPORTS_DIR", reports_dir)
        monkeypatch.setattr(
            gen, "get_connection", lambda: _NoCloseConn(conn),
        )

        gen._write_positioning_bundle(
            slug="slug-snap",
            team_id=1,
            public_id="opp-bears",
            season_id=_SEASON,
            opponent_name="Opp Bears",
            freshness_date="2026-04-12",
            game_count=12,
        )
        snapshot_path = reports_dir / "slug-snap" / "bundle_snapshot.json"
        assert snapshot_path.exists()
        snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
        assert snapshot["public_id"] == "opp-bears"
        assert snapshot["season_id"] == _SEASON
        assert snapshot["opponent_name"] == "Opp Bears"
        assert snapshot["through_date"] == "Apr 12"
        assert snapshot["game_count"] == 12


class TestRegenerateBundleFromSnapshot:
    """AC-6(e): the coverage-cue text survives a re-render even when
    the underlying DB freshness has advanced (the snapshot is the
    source of truth, not the live DB)."""

    def test_regenerate_uses_snapshot_not_live_freshness(
        self, conn, tmp_path, monkeypatch,
    ):
        _seed_full_opponent(conn)
        import src.reports.generator as gen
        reports_dir = tmp_path / "data" / "reports"
        monkeypatch.setattr(gen, "_REPO_ROOT", tmp_path)
        monkeypatch.setattr(gen, "_REPORTS_DIR", reports_dir)
        monkeypatch.setattr(
            gen, "get_connection", lambda: _NoCloseConn(conn),
        )

        # First generation: snapshot captures Apr 12 / 12 games.
        gen._write_positioning_bundle(
            slug="slug-rerun",
            team_id=1,
            public_id="opp-bears",
            season_id=_SEASON,
            opponent_name="Opp Bears",
            freshness_date="2026-04-12",
            game_count=12,
        )
        bundle_path = reports_dir / "slug-rerun" / "index.html"
        html_v1 = bundle_path.read_text(encoding="utf-8")
        assert "Through Apr 12 (12 games)" in html_v1

        # Mutate the DB to mimic later scouting -- if the re-render
        # consulted live data the cue would change. Bumping aggregate
        # counts is enough to prove the re-render relies on snapshot,
        # not freshness query.
        for p in COVERED_POSITIONS:
            conn.execute(
                "UPDATE team_position_aggregate SET bip_count = 999 "
                "WHERE position = ? AND team_id = 1",
                (p,),
            )
        conn.commit()

        # Regenerate from the persisted snapshot.
        rel_path = gen.regenerate_positioning_bundle("slug-rerun")
        assert rel_path.endswith("slug-rerun/index.html")
        html_v2 = bundle_path.read_text(encoding="utf-8")

        # AC-6(e) invariance: the coverage cue text is present in
        # both renders with the same count. (The body HTML may differ
        # slightly because cards reflect the bumped bip_count, but the
        # header cue is fed from the snapshot kwargs, which haven't
        # changed.)
        assert "Through Apr 12 (12 games)" in html_v2
        v1_cue_count = html_v1.count("Through Apr 12 (12 games)")
        v2_cue_count = html_v2.count("Through Apr 12 (12 games)")
        assert v1_cue_count == v2_cue_count

    def test_regenerate_raises_when_snapshot_missing(
        self, tmp_path, monkeypatch,
    ):
        import src.reports.generator as gen
        reports_dir = tmp_path / "data" / "reports"
        monkeypatch.setattr(gen, "_REPO_ROOT", tmp_path)
        monkeypatch.setattr(gen, "_REPORTS_DIR", reports_dir)
        with pytest.raises(FileNotFoundError, match="No bundle snapshot"):
            gen.regenerate_positioning_bundle("never-generated")


# ---------------------------------------------------------------------------
# F3 (codex P2 pre-closure triage): cards perspective fallback
# ---------------------------------------------------------------------------


class TestCardsPerspectiveFallback:
    """F3: when an opponent's positioning data exists only under a
    non-standalone perspective (e.g., ``perspective_team_id = 99``,
    the member team's perspective), the bundle's cards section MUST
    render that data via prefer-then-fallback. Prior to remediation the
    bundle hard-filtered on ``perspective_team_id = team_id`` and
    silently dropped the cards section; the call sheet + prep page
    already used the prefer-then-fallback pattern, so the bug was a
    user-visible asymmetry between the three sections."""

    def test_cards_section_renders_when_only_opponent_perspective(
        self, conn,
    ):
        """Repro per Codex F3: seed aggregates + batter rows ONLY under
        ``perspective_team_id = 99`` (the LSB member team's
        perspective) and assert the rendered bundle still shows the
        batter's outlier zone in the cards section."""
        # Standard fixture except perspective_team_id is forced to 99
        # (the member team), simulating data sourced via the member's
        # boxscore-scouting view of the opponent.
        for p in COVERED_POSITIONS:
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 99, ?, 160.0, 200.0, 60, 0)
                """,
                (_SEASON, p),
            )
        _seed_player(conn, "p1", "Hank", "Ramirez")
        _seed_roster(conn, "p1", "7")
        _seed_batter_row(
            conn, player_id="p1", position="LF",
            zone_id="A", direction_deviation=-1, depth_deviation=-1,
            perspective_team_id=99,
        )
        for p in ("CF", "RF", "3B", "SS", "2B"):
            _seed_batter_row(
                conn, player_id="p1", position=p,
                perspective_team_id=99,
            )
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Cards section is present (the section wrapper renders even
        # in the zero-coverage state, so this alone proves nothing).
        assert "positioning-cards-sheet" in html
        # The cards section must actually render the batter -- the
        # prior bug left the section in the "no outliers" empty state
        # because _query_cards_positioning_rows returned [].
        assert "RAMIREZ" in html

    def test_choose_perspective_prefers_standalone(self, conn):
        """When BOTH standalone (perspective=team_id=1) AND non-
        standalone (perspective=99) rows exist, the chosen perspective
        MUST be the standalone one to match the sibling render helpers."""
        from src.reports.positioning_bundle import _choose_perspective_team_id

        for p in COVERED_POSITIONS:
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 1, ?, 160.0, 200.0, 60, 0)
                """,
                (_SEASON, p),
            )
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 99, ?, 160.0, 200.0, 60, 0)
                """,
                (_SEASON, p),
            )
        conn.commit()
        assert _choose_perspective_team_id(conn, 1, _SEASON) == 1

    def test_choose_perspective_falls_back_when_standalone_absent(
        self, conn,
    ):
        """When ONLY a non-standalone perspective exists, fall back to
        it (return ``99``) rather than returning None."""
        from src.reports.positioning_bundle import _choose_perspective_team_id

        for p in COVERED_POSITIONS:
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 99, ?, 160.0, 200.0, 60, 0)
                """,
                (_SEASON, p),
            )
        conn.commit()
        assert _choose_perspective_team_id(conn, 1, _SEASON) == 99

    def test_choose_perspective_returns_none_when_no_aggregates(self, conn):
        from src.reports.positioning_bundle import _choose_perspective_team_id
        assert _choose_perspective_team_id(conn, 1, _SEASON) is None


# ---------------------------------------------------------------------------
# F2 (codex P1 pre-closure triage): page-4 slot-3 + slot-4 content
# ---------------------------------------------------------------------------


class TestOpponentContextPayload:
    """F2 (b): the `_build_opponent_context` helper builds the page-4
    slot-3 + slot-4 template-context payload per UXD's locked spec."""

    def _seed_games(self, conn, *, scored: int = 32, allowed: int = 14):
        """Seed 5 completed games for team_id=1 so the runs-per-game +
        record queries have data. Per-game scoring distributes the
        ``scored`` / ``allowed`` totals across 5 games."""
        # Distribute scored = 32, allowed = 14 -> 6.4 / 2.8 per game.
        per_game = [
            (1, 99, 8, 2),
            (99, 1, 5, 6),
            (1, 99, 7, 4),
            (99, 1, 3, 8),
            (1, 99, 3, 0),
        ]
        for idx, (home, away, hs, as_) in enumerate(per_game):
            conn.execute(
                """
                INSERT INTO games (
                    game_id, season_id, home_team_id, away_team_id,
                    home_score, away_score, game_date
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (f"g{idx}", _SEASON, home, away, hs, as_,
                 f"2026-03-{idx + 1:02d}"),
            )
        conn.commit()

    def test_full_tier(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)  # team aggregates bip_count=60, low_conf=0
        self._seed_games(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=12, today="2026-05-01",
        )
        assert "Full" in ctx["opponent_context_tier_line"]
        assert ("outlier markers and density background"
                in ctx["opponent_context_tier_line"])

    def test_thin_tier(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        for p in COVERED_POSITIONS:
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 1, ?, 160.0, 200.0, 30, 1)
                """,
                (_SEASON, p),
            )
        conn.commit()
        self._seed_games(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=5, today="2026-05-01",
        )
        assert "Thin" in ctx["opponent_context_tier_line"]
        assert "thin-tier indicators" in ctx["opponent_context_tier_line"]

    def test_zero_tier(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        for p in COVERED_POSITIONS:
            conn.execute(
                """
                INSERT INTO team_position_aggregate (
                    team_id, season_id, perspective_team_id, position,
                    star_x, star_y, bip_count, is_low_confidence
                ) VALUES (1, ?, 1, ?, 160.0, 200.0, 8, 1)
                """,
                (_SEASON, p),
            )
        conn.commit()
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=1, today="2026-05-01",
        )
        assert "Zero" in ctx["opponent_context_tier_line"]
        assert "not enough spray data" in ctx["opponent_context_tier_line"]

    def test_stats_list_has_four_rows_in_fixed_order(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)
        self._seed_games(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=12, today="2026-05-01",
        )
        stats = ctx["opponent_context_stats"]
        assert len(stats) == 4
        labels = [s["label"] for s in stats]
        assert labels == [
            "Record", "Runs / game", "Runs allowed / game", "Team BIPs",
        ]
        # Record: team 1 wins all 5 (home-wins: g0, g2, g4 with 8>2,
        # 7>4, 3>0; away-wins: g1, g3 with 6>5, 8>3).
        assert stats[0]["value"] == "5–0"
        # Runs scored avg = (8+6+7+8+3)/5 = 6.4
        assert stats[1]["value"] == "6.4"
        # Runs allowed avg = (2+5+4+3+0)/5 = 2.8
        assert stats[2]["value"] == "2.8"
        # Team BIPs from any aggregate row = 60.
        assert stats[3]["value"] == "60"

    def test_compass_key_svg_present(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=12, today="2026-05-01",
        )
        svg = ctx["compass_key_svg"]
        assert svg.startswith("<svg")
        assert svg.endswith("</svg>")
        for letter in "ABCDEFGH":
            assert f">{letter}<" in svg, f"missing zone letter {letter}"
        for axis in ("DEEP", "IN", "LEFT", "RIGHT"):
            assert f">{axis}<" in svg, f"missing axis label {axis}"

    def test_coverage_line_includes_season_and_count_and_versus(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)
        # Schedule one upcoming game so the "vs. {us} {date}" suffix
        # has data.
        conn.execute(
            """
            INSERT INTO games (
                game_id, season_id, home_team_id, away_team_id, game_date
            ) VALUES ('g-up', ?, 1, 99, '2026-06-15')
            """,
            (_SEASON,),
        )
        conn.commit()
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=99,
            game_count=12, today="2026-05-01",
        )
        line = ctx["opponent_context_coverage_line"]
        assert "2026" in line
        assert "12 games" in line
        assert "LSB Varsity" in line
        assert "2026-06-15" in line

    def test_coverage_line_degrades_when_no_upcoming_game(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=99,
            game_count=12, today="2026-05-01",
        )
        line = ctx["opponent_context_coverage_line"]
        assert "vs. LSB Varsity" in line
        # No upcoming game seeded -> trailing date omitted.
        assert "vs. LSB Varsity" in line
        assert "2026-06" not in line  # no upcoming date

    def test_singular_game_word(self, conn):
        from src.reports.positioning_bundle import _build_opponent_context
        _seed_full_opponent(conn)
        ctx = _build_opponent_context(
            conn,
            team_id=1, season_id=_SEASON, perspective_team_id=1,
            game_count=1, today="2026-05-01",
        )
        # "1 game" not "1 games".
        assert "1 game" in ctx["opponent_context_coverage_line"]
        assert "1 games" not in ctx["opponent_context_coverage_line"]


class TestBundleThreadsCompassKeyAndOpponentContext:
    """F2 (c): the rendered bundle HTML includes the compass-key SVG
    body content AND the 4 opponent-context stat rows."""

    def test_bundle_renders_compass_key_letters(self, conn):
        _seed_full_opponent(conn)
        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Slot 3's SVG body content: every compass letter A-H must
        # appear inside a <text> element in the slot-3 SVG. (Many of
        # those letters may also appear elsewhere in zone-letter cells
        # in the call sheet / cards, so we scope to the slot div and
        # its SVG body specifically.)
        slot3_start = html.find(
            'class="positioning-card compass-key"',
        )
        assert slot3_start > 0, "compass-key slot div not rendered"
        svg_start = html.find("<svg", slot3_start)
        svg_end = html.find("</svg>", svg_start) + len("</svg>")
        assert svg_start > slot3_start and svg_end > svg_start, (
            "compass-key slot must contain an inline <svg> body"
        )
        svg_body = html[svg_start:svg_end]
        for letter in "ABCDEFGH":
            assert f">{letter}<" in svg_body, (
                f"compass-key slot SVG missing letter {letter}"
            )
        for axis in ("DEEP", "IN", "LEFT", "RIGHT"):
            assert f">{axis}<" in svg_body, (
                f"compass-key slot SVG missing axis label {axis}"
            )

    def test_bundle_renders_opponent_context_stats(self, conn):
        _seed_full_opponent(conn)
        # Seed games so the runs / record queries return data.
        per_game = [
            (1, 99, 8, 2),
            (99, 1, 5, 6),
            (1, 99, 7, 4),
        ]
        for idx, (home, away, hs, as_) in enumerate(per_game):
            conn.execute(
                """
                INSERT INTO games (
                    game_id, season_id, home_team_id, away_team_id,
                    home_score, away_score, game_date
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (f"g{idx}", _SEASON, home, away, hs, as_,
                 f"2026-03-{idx + 1:02d}"),
            )
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        for stat_label in ("Record", "Runs / game", "Runs allowed / game", "Team BIPs"):
            assert stat_label in html, f"missing opponent-context stat: {stat_label}"
        # Tier line copy.
        assert "Coverage tier:" in html
        assert "Full" in html

    def test_bundle_renders_when_no_aggregate_rows(self, conn):
        """When there's no aggregate, F2 payload is skipped but the
        bundle still ships -- slots 3 + 4 fall back to template
        defaults."""
        # No aggregates seeded; only a player.
        _seed_player(conn, "p1", "Hank", "Ramirez")
        _seed_roster(conn, "p1", "7")
        conn.commit()

        html = generate_positioning_bundle(
            conn, "opp-bears", _SEASON,
            opponent_name="Opp Bears",
            through_date="Apr 12", game_count=12,
        )
        # Bundle still produces all four sections.
        assert "positioning-call-sheet" in html
        assert "positioning-prep-page" in html
        assert "positioning-cards-sheet" in html
