"""Tests for the standalone scouting report renderer (E-172-01)."""

from __future__ import annotations

from unittest.mock import patch

import pytest

from src.reports.renderer import render_report


def _make_pitcher(
    name: str = "John Smith",
    jersey_number: int | None = 12,
    ip_outs: int = 60,
    **overrides,
) -> dict:
    """Build a pitcher stat dict with sensible defaults."""
    base = {
        "name": name,
        "jersey_number": jersey_number,
        "era": "2.50",
        "k9": "9.0",
        "whip": "1.10",
        "games": 8,
        "ip_outs": ip_outs,
        "h": 20,
        "er": 5,
        "bb": 10,
        "so": 30,
        "pitches": 400,
        "strike_pct": "62%",
    }
    base.update(overrides)
    return base


def _make_batter(
    name: str = "Jane Doe",
    jersey_number: int | None = 7,
    ab: int = 50,
    player_id: int = 100,
    **overrides,
) -> dict:
    """Build a batter stat dict with sensible defaults."""
    base = {
        "player_id": player_id,
        "name": name,
        "jersey_number": jersey_number,
        "games": 12,
        "ab": ab,
        "h": 15,
        "bb": 8,
        "hbp": 1,
        "shf": 0,
        "doubles": 3,
        "triples": 1,
        "hr": 2,
        "rbi": 10,
        "so": 12,
        "sb": 4,
    }
    base.update(overrides)
    return base


def _make_full_data(**overrides) -> dict:
    """Build a complete report data dict."""
    base = {
        "team": {
            "name": "Test Tigers",
            "season_year": 2026,
            "record": {"wins": 15, "losses": 5},
        },
        "generated_at": "2026-03-28T12:00:00Z",
        "expires_at": "2026-04-11T12:00:00Z",
        "freshness_date": "2026-03-25",
        "game_count": 20,
        "recent_form": [
            {"result": "W", "our_score": 7, "their_score": 3},
            {"result": "L", "our_score": 2, "their_score": 4},
            {"result": "W", "our_score": 5, "their_score": 1},
        ],
        "pitching": [_make_pitcher()],
        "batting": [_make_batter()],
        "spray_charts": {},
        "roster": [
            {"jersey_number": 7, "name": "Jane Doe", "position": "SS"},
            {"jersey_number": 12, "name": "John Smith", "position": "P"},
        ],
    }
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# AC-9(a): Renderer produces valid HTML containing expected sections
# ---------------------------------------------------------------------------


class TestCompleteReport:
    """Test renderer output with complete data."""

    def test_produces_html_with_all_sections(self):
        data = _make_full_data()
        html = render_report(data)

        assert "<!DOCTYPE html>" in html
        assert "Test Tigers" in html
        assert "Scouting Report" in html
        # Header meta
        assert "2026" in html
        assert "15-5" in html
        # Freshness (AC-6)
        assert "Mar 25" in html
        assert "20 games" in html
        # Recent form
        assert "Recent Form:" in html
        assert "W 7-3" in html
        assert "L 2-4" in html
        # Pitching section
        assert "Pitching" in html
        assert "John Smith" in html
        assert "2.50" in html  # ERA
        # Batting section
        assert "Batting" in html
        assert "Jane Doe" in html
        # Roster
        assert "Roster" in html
        assert "#7" in html
        assert "SS" in html
        # Footer
        assert "Generated by bbstats.ai" in html
        assert "2026-03-28" in html
        assert "Expires" in html
        assert "2026-04-11" in html

    def test_html_is_self_contained_no_external_urls(self):
        data = _make_full_data()
        html = render_report(data)

        # No external CSS/JS/image links
        assert "http://" not in html
        assert "https://" not in html
        assert "<link" not in html.lower()
        assert '<script src' not in html.lower()

    def test_print_css_rules_present(self):
        data = _make_full_data()
        html = render_report(data)

        assert "@media print" in html
        assert "page-break-inside: avoid" in html
        assert "size: landscape" in html

    def test_mobile_css_rules_present(self):
        data = _make_full_data()
        html = render_report(data)

        assert "@media screen and (max-width: 640px)" in html

    def test_print_button_present(self):
        data = _make_full_data()
        html = render_report(data)

        assert "Print / Save as PDF" in html
        assert "screen-only" in html

    def test_pitching_columns_match_opponent_view(self):
        """Verify pitching table has the expected column headers."""
        data = _make_full_data()
        html = render_report(data)

        for col in ["ERA", "K/9", "WHIP", "GP", "IP", "H", "ER", "BB", "SO", "#P", "Strike%"]:
            assert f">{col}<" in html or f">{col}</th>" in html

    def test_batting_columns_match_opponent_view(self):
        """Verify batting table has the expected column headers."""
        data = _make_full_data()
        html = render_report(data)

        for col in ["AVG", "OBP", "SLG", "GP", "AB", "H", "2B", "3B", "HR", "RBI", "BB", "SO", "SB"]:
            assert f">{col}<" in html or f">{col}</th>" in html


# ---------------------------------------------------------------------------
# AC-9(b): Spray charts appear as base64 data URIs
# ---------------------------------------------------------------------------


class TestSprayCharts:
    """Test spray chart rendering and embedding."""

    def test_spray_charts_as_base64_data_uris(self):
        """AC-9(b): Spray charts embedded as data:image/png;base64."""
        batter = _make_batter(player_id=42)
        events = [
            {"x": 150.0, "y": 200.0, "play_result": "single", "play_type": "line_drive"}
            for _ in range(12)
        ]
        data = _make_full_data(
            batting=[batter],
            spray_charts={42: events},
        )

        # Mock render_spray_chart to avoid matplotlib rendering in tests
        fake_png = b"\x89PNG_FAKE_DATA"
        with patch("src.reports.renderer.render_spray_chart", return_value=fake_png):
            html = render_report(data)

        assert "data:image/png;base64," in html
        # The base64-encoded fake PNG should be present
        import base64
        expected_b64 = base64.b64encode(fake_png).decode("ascii")
        assert expected_b64 in html

    def test_spray_charts_below_threshold_excluded(self):
        """Players with fewer than 10 BIP have no spray chart."""
        batter = _make_batter(player_id=42)
        events = [
            {"x": 150.0, "y": 200.0, "play_result": "single", "play_type": "ground_ball"}
            for _ in range(5)  # Below 10 BIP threshold
        ]
        data = _make_full_data(
            batting=[batter],
            spray_charts={42: events},
        )

        html = render_report(data)

        assert "data:image/png;base64," not in html
        assert "Batter Tendencies" not in html


# ---------------------------------------------------------------------------
# AC-9(c): Missing spray chart data => section omitted
# ---------------------------------------------------------------------------


class TestMissingSprayCharts:
    """Test behavior when spray chart data is absent."""

    def test_no_spray_charts_key(self):
        data = _make_full_data()
        del data["spray_charts"]
        html = render_report(data)

        assert "Batter Tendencies" not in html
        assert "data:image/png;base64," not in html

    def test_empty_spray_charts(self):
        data = _make_full_data(spray_charts={})
        html = render_report(data)

        assert "Batter Tendencies" not in html

    def test_spray_charts_none(self):
        data = _make_full_data(spray_charts=None)
        html = render_report(data)

        assert "Batter Tendencies" not in html


# ---------------------------------------------------------------------------
# AC-9(d): Missing stats produce "No data available"
# ---------------------------------------------------------------------------


class TestMissingStats:
    """Test graceful handling of missing stat data."""

    def test_empty_pitching_shows_no_data(self):
        data = _make_full_data(pitching=[])
        html = render_report(data)

        # The pitching section header should be present
        assert "Pitching" in html
        assert "No data available" in html

    def test_empty_batting_shows_no_data(self):
        data = _make_full_data(batting=[])
        html = render_report(data)

        assert "Batting" in html
        assert "No data available" in html

    def test_none_pitching_shows_no_data(self):
        data = _make_full_data(pitching=None)
        html = render_report(data)

        assert "No data available" in html

    def test_none_batting_shows_no_data(self):
        data = _make_full_data(batting=None)
        html = render_report(data)

        assert "No data available" in html

    def test_missing_schedule_omits_recent_form(self):
        """AC-8: If schedule data is absent, recent form section is omitted."""
        data = _make_full_data(recent_form=None)
        html = render_report(data)

        assert "Recent Form:" not in html

    def test_empty_recent_form_omits_section(self):
        data = _make_full_data(recent_form=[])
        html = render_report(data)

        assert "Recent Form:" not in html


# ---------------------------------------------------------------------------
# AC-9(e): Data freshness line appears in header
# ---------------------------------------------------------------------------


class TestFreshnessLine:
    """Test the data freshness line in the header."""

    def test_freshness_date_appears(self):
        data = _make_full_data(freshness_date="2026-03-25", game_count=20)
        html = render_report(data)

        assert "Mar 25" in html
        assert "20 games" in html

    def test_freshness_date_none_omits_through(self):
        data = _make_full_data(freshness_date=None, game_count=5)
        html = render_report(data)

        assert "Stats through" not in html
        assert "5 games" in html

    def test_zero_games_no_freshness(self):
        data = _make_full_data(freshness_date=None, game_count=0)
        html = render_report(data)

        # Freshness content should not render when both are falsy
        assert "Stats through" not in html
        assert "0 games" not in html


# ---------------------------------------------------------------------------
# AC-9(f): Small sample indicator for low-PA/IP players
# ---------------------------------------------------------------------------


class TestSmallSampleFlags:
    """Test small sample size asterisk indicators."""

    def test_pitching_small_sample_asterisk(self):
        """Pitcher with < 15 IP (45 outs) gets asterisk."""
        pitcher = _make_pitcher(ip_outs=30, name="Low IP Pitcher")  # 10 IP
        data = _make_full_data(pitching=[pitcher])
        html = render_report(data)

        assert "Low IP Pitcher *" in html or "Low IP Pitcher\n *" in html or "Low IP Pitcher *" in html
        assert "Small sample size" in html
        assert "fewer than 15 IP" in html

    def test_pitching_no_asterisk_above_threshold(self):
        """Pitcher with >= 15 IP (45 outs) has no asterisk."""
        pitcher = _make_pitcher(ip_outs=60, name="High IP Pitcher")  # 20 IP
        data = _make_full_data(pitching=[pitcher])
        html = render_report(data)

        assert "High IP Pitcher *" not in html
        # Footnote should not appear if no small samples
        assert "fewer than 15 IP" not in html

    def test_batting_small_sample_asterisk(self):
        """Batter with < 20 PA gets asterisk."""
        batter = _make_batter(ab=10, name="Low PA Batter")
        # PA = ab + bb + hbp + shf = 10 + 8 + 1 + 0 = 19 < 20
        data = _make_full_data(batting=[batter])
        html = render_report(data)

        assert "Low PA Batter *" in html or "Low PA Batter\n *" in html
        assert "Small sample size" in html
        assert "fewer than 20 PA" in html

    def test_batting_no_asterisk_above_threshold(self):
        """Batter with >= 20 PA has no asterisk."""
        batter = _make_batter(ab=50, name="High PA Batter")
        # PA = 50 + 8 + 1 + 0 = 59 >= 20
        data = _make_full_data(batting=[batter])
        html = render_report(data)

        assert "High PA Batter *" not in html
        assert "fewer than 20 PA" not in html

    def test_mixed_sample_sizes_only_flags_small(self):
        """Only players below threshold get the asterisk."""
        small = _make_batter(ab=5, name="Small Sample", player_id=1)
        # PA = 5 + 8 + 1 + 0 = 14 < 20
        large = _make_batter(ab=50, name="Large Sample", player_id=2)
        # PA = 50 + 8 + 1 + 0 = 59 >= 20
        data = _make_full_data(batting=[small, large])
        html = render_report(data)

        assert "Small Sample *" in html or "Small Sample\n *" in html
        assert "Large Sample *" not in html
        assert "fewer than 20 PA" in html


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Test edge cases and robustness."""

    def test_missing_team_record(self):
        data = _make_full_data()
        data["team"]["record"] = None
        html = render_report(data)

        assert "Test Tigers" in html
        # Should not crash

    def test_missing_season_year(self):
        data = _make_full_data()
        data["team"]["season_year"] = None
        html = render_report(data)

        assert "Test Tigers" in html

    def test_empty_roster(self):
        data = _make_full_data(roster=[])
        html = render_report(data)

        # The roster section header should not appear (CSS class names will)
        assert ">Roster<" not in html

    def test_pitcher_missing_pitches(self):
        pitcher = _make_pitcher(pitches=None, strike_pct=None)
        data = _make_full_data(pitching=[pitcher])
        html = render_report(data)

        # Should render mdash for missing values, not crash
        assert "John Smith" in html

    def test_spray_chart_render_failure_is_non_fatal(self):
        """If spray chart rendering raises, the chart is skipped."""
        batter = _make_batter(player_id=42)
        events = [
            {"x": 150.0, "y": 200.0, "play_result": "single", "play_type": "line_drive"}
            for _ in range(12)
        ]
        data = _make_full_data(batting=[batter], spray_charts={42: events})

        with patch("src.reports.renderer.render_spray_chart", side_effect=RuntimeError("render failed")):
            html = render_report(data)

        # Should not crash; spray section should be omitted
        assert "Batter Tendencies" not in html
        assert "<!DOCTYPE html>" in html

    def test_single_game_count_singular(self):
        data = _make_full_data(game_count=1)
        html = render_report(data)
        assert "1 game" in html
        assert "1 games" not in html
