-- ===========================================================================
-- Migration 004: webauthn_challenges
-- ===========================================================================
-- Epic E-238 (story E-238-06), Technical Notes "Passkey challenge store".
--
-- WHAT: Adds a TTL'd `webauthn_challenges` table that replaces the two
--       in-process module-global dicts (`_PASSKEY_LOGIN_CHALLENGES`,
--       `_PASSKEY_REG_CHALLENGES`) in `src/api/routes/auth.py`.
--
-- WHY:  The in-memory dicts are single-worker-only and lost on restart
--       mid-login -- a real auth bug. With `--workers N > 1` a challenge
--       generated by one worker is invisible to the worker that handles the
--       verify request, silently breaking passkey login; an app restart
--       between options and verify does the same. Storing challenges in
--       SQLite makes login survive multiple workers and restarts, because all
--       workers share `data/app.db` (WAL on).
--
-- DESIGN:
--   One row per outstanding challenge, keyed by (kind, lookup_key):
--     * login        -- keyed by the challenge itself (anonymous; no session
--                       exists yet, matches the old dict whose key WAS the
--                       challenge_b64).
--     * registration -- keyed by the session-id hash (SHA-256 of the cookie
--                       token). A repeat GET /passkey/register overwrites the
--                       prior challenge via ON CONFLICT DO UPDATE.
--   `challenge` is the standard-base64 challenge string (what py_webauthn
--   verifies against). No FK / no user_id -- login challenges are issued
--   before any user identity exists, and the DB only gates
--   live-and-unconsumed; py_webauthn remains the cryptographic check.
--
-- TTL:  `expires_at` is SQLite datetime TEXT everywhere (aligns with
--       `sessions` / `magic_link_tokens`) -- NEVER epoch floats. The 5-minute
--       window matches the old `_PASSKEY_CHALLENGE_TTL = 300`. Enforcement is
--       two-sided, with no background job:
--         * read  -- a live-row gate (`expires_at > datetime('now')`).
--         * write -- a sweep (`DELETE WHERE expires_at <= datetime('now')`) at
--                    each create, replacing the old `_purge_expired_challenges`.
--       Replay protection is DELETE-on-consume (the consumed row is removed
--       after py_webauthn verifies) -- not a mark-used flag.
--
--   NOTE: SQLite column defaults that call functions MUST be parenthesized
--   (a bare `DEFAULT datetime(...)` is a syntax error).
--
-- IDEMPOTENCY: pure CREATE TABLE / CREATE INDEX IF NOT EXISTS -- concatenation
--   safe for `conftest.load_real_schema`, which globs and concatenates every
--   numbered migration. No ALTER, so the SQLite "no ADD COLUMN IF NOT EXISTS"
--   caveat never applies.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS webauthn_challenges (
    -- 'login' or 'registration' -- the two challenge flows.
    kind        TEXT NOT NULL CHECK(kind IN ('login', 'registration')),
    -- login: the challenge_b64 itself (anonymous). registration: session-id hash.
    lookup_key  TEXT NOT NULL,
    -- standard-base64 challenge string py_webauthn verifies against.
    challenge   TEXT NOT NULL,
    -- TTL as SQLite datetime text; default = now + 5 minutes (parenthesized).
    expires_at  TEXT NOT NULL DEFAULT (datetime('now', '+5 minutes')),
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (kind, lookup_key)
);

-- Sweep-on-write deletes by the TTL column (`DELETE WHERE expires_at <= ...`),
-- so an index on expires_at keeps the per-create sweep from scanning the table.
-- No other (speculative) indexes -- reads are PK lookups on (kind, lookup_key).
CREATE INDEX IF NOT EXISTS idx_webauthn_challenges_expires_at
    ON webauthn_challenges(expires_at);
