"""Aggregate parity guard -- diff stored season aggregates vs a recompute.

Stored ``player_season_batting`` / ``player_season_pitching`` aggregate rows
can silently diverge from their source ``player_game_*`` rows.  Two scenarios
produce this (ROADMAP Section 2):

* a post-load player-dedup merge re-points game rows to a surviving
  ``player_id`` *after* the season aggregate was computed, leaving the stored
  season row reflecting the pre-merge grouping; or
* any other post-load mutation of the per-game rows.

This module recomputes the season aggregates from the per-game rows -- mirroring
``ScoutingLoader._compute_batting_aggregates`` / ``_compute_pitching_aggregates``
*exactly* (perspective filter, ``JOIN games`` on ``season_id``,
``GROUP BY player_id``, and the verbatim ``gs`` NULL-safe CASE) -- and diffs the
result against the stored rows.  Any difference is a real finding, not a false
positive: on a freshly-loaded DB with no post-load mutation the diff is empty.

Scope:

* Only ``stat_completeness = 'boxscore_only'`` season rows are checked.  Member
  season-stats-loader rows (``full`` / ``supplemented``) come straight from the
  API, are not summed from game rows, and would produce spurious mismatches.
* Only the SUM-computed column subset the ScoutingLoader writes is diffed
  (see ``_BATTING_COLUMNS`` / ``_PITCHING_COLUMNS``).  Member-only columns
  (``pa``, ``singles``, splits, qab/hard/weak/ps/sw, home/away, vs-LHP/RHP) are
  out of scope on provenance grounds -- not NULL-ness -- whether NULL or
  populated.  Pitching ``hr`` is deliberately not stored by the loader, so it
  is not diffed.

The recompute is strictly read-only; this module never writes to
``player_season_*``.  It is also the Epic C cutover gate: a stable
``bb report verify-aggregates`` to run against a production DB copy before the
payload-first loader cutover.  The static SQL fixture
(``tests/fixtures/parity_consistent.sql``) is the fixed anchor for the
green-path test and must survive Epic C untouched.

Maintenance invariant (review-enforced, NOT test-enforced): the parity test
never runs ScoutingLoader, so it cannot detect loader-semantic drift on its
own.  On any change to ``_compute_*_aggregates`` that alters the aggregate
CONTRACT (a SUM-subset column added/removed, or the ``gs`` definition), update
BOTH the recompute query here AND ``tests/fixtures/parity_consistent.sql``'s
expected values in lock-step -- and the updated fixture values must be
hand-recomputed independently from the game rows, never regenerated by dumping
loader output.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Diffed column sets
# ---------------------------------------------------------------------------
# Each entry maps a stored ``player_season_*`` column to the key under which the
# recompute exposes its value.  ``gp`` / ``games_tracked`` (batting) and
# ``gp_pitcher`` / ``games_tracked`` (pitching) all map to the per-group
# ``COUNT(*)`` -- the loader writes that count into both columns.

# Batting (16): gp == games_tracked == COUNT(*).
_BATTING_COLUMNS: tuple[tuple[str, str], ...] = (
    ("gp", "games_tracked"),
    ("games_tracked", "games_tracked"),
    ("ab", "ab"),
    ("h", "h"),
    ("doubles", "doubles"),
    ("triples", "triples"),
    ("hr", "hr"),
    ("rbi", "rbi"),
    ("r", "r"),
    ("bb", "bb"),
    ("so", "so"),
    ("sb", "sb"),
    ("tb", "tb"),
    ("hbp", "hbp"),
    ("shf", "shf"),
    ("cs", "cs"),
)

# Pitching (14): gp_pitcher == games_tracked == COUNT(*).  Pitching ``hr`` is
# deliberately NOT stored by the loader -- do not diff it.
_PITCHING_COLUMNS: tuple[tuple[str, str], ...] = (
    ("gp_pitcher", "games_tracked"),
    ("games_tracked", "games_tracked"),
    ("ip_outs", "ip_outs"),
    ("h", "h"),
    ("r", "r"),
    ("er", "er"),
    ("bb", "bb"),
    ("so", "so"),
    ("wp", "wp"),
    ("hbp", "hbp"),
    ("pitches", "pitches"),
    ("total_strikes", "total_strikes"),
    ("bf", "bf"),
    ("gs", "gs"),
)

# Recompute SELECT -- mirrors ScoutingLoader._compute_batting_aggregates EXACTLY
# (minus the INSERT): perspective filter, JOIN games on game_id, GROUP BY
# player_id.  The trailing key order matches ``_BATTING_RECOMPUTE_KEYS``.
_BATTING_RECOMPUTE_SQL = """
    SELECT
        pgb.player_id,
        COUNT(*)         AS games_tracked,
        SUM(pgb.ab)      AS ab,
        SUM(pgb.h)       AS h,
        SUM(pgb.doubles) AS doubles,
        SUM(pgb.triples) AS triples,
        SUM(pgb.hr)      AS hr,
        SUM(pgb.rbi)     AS rbi,
        SUM(pgb.r)       AS r,
        SUM(pgb.bb)      AS bb,
        SUM(pgb.so)      AS so,
        SUM(pgb.sb)      AS sb,
        SUM(pgb.tb)      AS tb,
        SUM(pgb.hbp)     AS hbp,
        SUM(pgb.shf)     AS shf,
        SUM(pgb.cs)      AS cs
    FROM player_game_batting pgb
    JOIN games g ON pgb.game_id = g.game_id
    WHERE pgb.team_id = ? AND g.season_id = ?
      AND pgb.perspective_team_id = ?
    GROUP BY pgb.player_id
"""

_BATTING_RECOMPUTE_KEYS = (
    "player_id", "games_tracked", "ab", "h", "doubles", "triples", "hr",
    "rbi", "r", "bb", "so", "sb", "tb", "hbp", "shf", "cs",
)

# Distinct (team_id, season_id) scopes present in the batting recompute source.
# Mirrors the recompute's perspective + JOIN filters (perspective_team_id =
# team_id, season_id via games) so the derived scopes match what the loader
# would have aggregated.
_BATTING_SOURCE_SCOPE_SQL = """
    SELECT DISTINCT pgb.team_id, g.season_id
    FROM player_game_batting pgb
    JOIN games g ON pgb.game_id = g.game_id
    WHERE pgb.perspective_team_id = pgb.team_id
"""

# Recompute SELECT -- mirrors ScoutingLoader._compute_pitching_aggregates EXACTLY
# (minus the INSERT), including the verbatim ``gs`` NULL-safe CASE:
# MAX(appearance_order) IS NULL -> NULL, else SUM(appearance_order = 1).
_PITCHING_RECOMPUTE_SQL = """
    SELECT
        pgp.player_id,
        COUNT(*)              AS games_tracked,
        SUM(pgp.ip_outs)      AS ip_outs,
        SUM(pgp.h)            AS h,
        SUM(pgp.r)            AS r,
        SUM(pgp.er)           AS er,
        SUM(pgp.bb)           AS bb,
        SUM(pgp.so)           AS so,
        SUM(pgp.wp)           AS wp,
        SUM(pgp.hbp)          AS hbp,
        SUM(pgp.pitches)      AS pitches,
        SUM(pgp.total_strikes) AS total_strikes,
        SUM(pgp.bf)           AS bf,
        CASE WHEN MAX(pgp.appearance_order) IS NULL THEN NULL
             ELSE SUM(CASE WHEN pgp.appearance_order = 1 THEN 1 ELSE 0 END)
        END AS gs
    FROM player_game_pitching pgp
    JOIN games g ON pgp.game_id = g.game_id
    WHERE pgp.team_id = ? AND g.season_id = ?
      AND pgp.perspective_team_id = ?
    GROUP BY pgp.player_id
"""

_PITCHING_RECOMPUTE_KEYS = (
    "player_id", "games_tracked", "ip_outs", "h", "r", "er", "bb", "so",
    "wp", "hbp", "pitches", "total_strikes", "bf", "gs",
)

# Distinct (team_id, season_id) scopes present in the pitching recompute source.
_PITCHING_SOURCE_SCOPE_SQL = """
    SELECT DISTINCT pgp.team_id, g.season_id
    FROM player_game_pitching pgp
    JOIN games g ON pgp.game_id = g.game_id
    WHERE pgp.perspective_team_id = pgp.team_id
"""


@dataclass(frozen=True)
class Mismatch:
    """A single diverging cell between a stored aggregate and the recompute."""

    player_id: str
    team_id: int
    season_id: str
    column: str
    stored: object
    recomputed: object


@dataclass
class ParityResult:
    """Outcome of a parity check.

    Attributes:
        mismatches: One entry per diverging ``(player_id, team_id, season_id,
            column)`` cell, with the stored and recomputed values.  Empty list
            means clean.
        cells_compared: Total cells examined (rows compared x diffed columns).
            A vacuous-pass guard: an empty ``mismatches`` list is only
            meaningful if ``cells_compared > 0``.
    """

    mismatches: list[Mismatch] = field(default_factory=list)
    cells_compared: int = 0


def _values_match(stored: object, recomputed: object) -> bool:
    """Exact integer equality with NULL-safe semantics.

    ``NULL == NULL`` is a match (e.g. a pitcher whose only appearance has a
    NULL ``appearance_order`` -> ``gs`` is NULL on both sides).  ``NULL`` vs a
    non-``NULL`` value is a mismatch.  No tolerance otherwise.
    """
    if stored is None and recomputed is None:
        return True
    return stored == recomputed


def _check_table(
    conn: sqlite3.Connection,
    *,
    season_table: str,
    recompute_sql: str,
    recompute_keys: tuple[str, ...],
    diff_columns: tuple[tuple[str, str], ...],
    source_scope_sql: str,
    member_scopes: frozenset[tuple[int, str]],
) -> tuple[list[Mismatch], int]:
    """Diff one stored season table against its per-game recompute.

    Scope derivation -- the set of ``(team_id, season_id)`` groups checked is
    the UNION of two sources:

    1. Groups present in the stored ``boxscore_only`` rows (the aggregates being
       validated).  Within each, the union of stored and recomputed
       ``player_id`` keys is examined so that a player missing from either side
       (the post-load-dedup staleness signature) surfaces as a mismatch
       (``stored`` or ``recomputed`` is ``None``).
    2. Groups present in the RECOMPUTE SOURCE (``player_game_*`` joined to
       ``games``, ``perspective_team_id = team_id``) that are NEITHER already a
       stored ``boxscore_only`` group (set 1) NOR a member-loaded group (see the
       discriminator below).  Such a group has game rows the loader would have
       summed into a ``boxscore_only`` aggregate, but no stored aggregate exists
       -- a genuinely missing write.  Without (2), an entire ``boxscore_only``
       rowset deleted from a scope would never be examined and the divergence
       would pass green (the Epic C cutover gate's worst failure mode).

    Member-loaded discriminator (avoids a FALSE POSITIVE) -- PROVENANCE-based,
    cross-table: the member season-stats loader writes ``full`` /
    ``supplemented`` rows straight from the API (not summed from game rows), and
    they are intentionally outside this gate.  Critically, that loader writes
    per player and per table independently -- ``_load_player`` writes a
    ``player_season_pitching`` row only when the player pitched -- and the
    per-game rows come from a DIFFERENT loader (the boxscore GameLoader).  So a
    member team+season can have ``player_game_pitching`` rows (perspective=team)
    yet ZERO ``player_season_pitching`` rows of any completeness (season-stats
    not loaded for that table, or no pitchers reported).  A single-table
    "zero stored rows here" test would then FLAG that scope using the boxscore
    SUM as the oracle -- a false positive, since the member's authoritative
    season value comes from the API, not the boxscore sum.  ``member_scopes``
    therefore carries every scope with a ``full`` / ``supplemented`` row in
    EITHER season table; any such scope is excluded from set (2) here even when
    its provenance evidence lives in the OTHER table.  A genuine scouting scope
    (boxscore_only everywhere, no full/supplemented) with one table's rows
    deleted has no member evidence in either table, so it is STILL flagged.
    """
    stored_columns = [stored_col for stored_col, _ in diff_columns]
    select_cols = ", ".join(["player_id", "team_id", "season_id", *stored_columns])
    stored_rows = conn.execute(
        f"SELECT {select_cols} FROM {season_table} "
        f"WHERE stat_completeness = 'boxscore_only'"
    ).fetchall()

    # stored[(team_id, season_id)][player_id] = {stored_col: value, ...}
    stored: dict[tuple[int, str], dict[str, dict[str, object]]] = {}
    for row in stored_rows:
        player_id, team_id, season_id = row[0], row[1], row[2]
        values = dict(zip(stored_columns, row[3:]))
        stored.setdefault((team_id, season_id), {})[player_id] = values

    # Scopes present in the recompute source (game rows, perspective=team).
    source_scopes = {
        (row[0], row[1]) for row in conn.execute(source_scope_sql).fetchall()
    }
    # A source scope that is neither already a stored boxscore_only group nor a
    # member-loaded group is a genuine missing aggregate: its stored side is
    # empty here -> every recomputed player surfaces as a (stored=None vs
    # recomputed) mismatch.
    missing_scopes = source_scopes - set(stored.keys()) - member_scopes

    mismatches: list[Mismatch] = []
    cells_compared = 0

    scopes = set(stored.keys()) | missing_scopes
    for (team_id, season_id) in scopes:
        stored_players = stored.get((team_id, season_id), {})
        recomputed_rows = conn.execute(
            recompute_sql, (team_id, season_id, team_id)
        ).fetchall()
        recomputed: dict[str, dict[str, object]] = {
            row[0]: dict(zip(recompute_keys[1:], row[1:]))
            for row in recomputed_rows
        }

        player_ids = sorted(set(stored_players) | set(recomputed))
        for player_id in player_ids:
            stored_values = stored_players.get(player_id)
            recomputed_values = recomputed.get(player_id)
            for stored_col, recompute_key in diff_columns:
                stored_val = (
                    stored_values.get(stored_col)
                    if stored_values is not None
                    else None
                )
                recomputed_val = (
                    recomputed_values.get(recompute_key)
                    if recomputed_values is not None
                    else None
                )
                cells_compared += 1
                if not _values_match(stored_val, recomputed_val):
                    mismatches.append(
                        Mismatch(
                            player_id=player_id,
                            team_id=team_id,
                            season_id=season_id,
                            column=stored_col,
                            stored=stored_val,
                            recomputed=recomputed_val,
                        )
                    )

    return mismatches, cells_compared


def _member_scopes(conn: sqlite3.Connection) -> frozenset[tuple[int, str]]:
    """Return every ``(team_id, season_id)`` with a member-provenance row.

    A scope is member-loaded if EITHER ``player_season_batting`` OR
    ``player_season_pitching`` holds a ``full`` / ``supplemented`` row for it.
    Such rows come from the member season-stats API (not summed from games) and
    are outside this gate; collecting them cross-table lets the missing-
    aggregate detection exclude a member scope even when its provenance evidence
    lives only in the other stat table (the asymmetric-member edge).
    """
    rows = conn.execute(
        """
        SELECT DISTINCT team_id, season_id FROM player_season_batting
            WHERE stat_completeness IN ('full', 'supplemented')
        UNION
        SELECT DISTINCT team_id, season_id FROM player_season_pitching
            WHERE stat_completeness IN ('full', 'supplemented')
        """
    ).fetchall()
    return frozenset((row[0], row[1]) for row in rows)


def verify_aggregates(conn: sqlite3.Connection) -> ParityResult:
    """Diff stored season aggregates against a per-game recompute.

    Recomputes batting and pitching season aggregates from ``player_game_*``
    (mirroring ``ScoutingLoader._compute_*_aggregates``) and diffs them against
    the stored ``player_season_*`` rows scoped to
    ``stat_completeness = 'boxscore_only'``.  Also flags scopes whose
    recompute-source game rows have no stored aggregate at all (a missing
    write), while excluding member-loaded (``full`` / ``supplemented``) scopes
    -- see :func:`_check_table`.  Read-only: never writes to the database.

    Args:
        conn: Open SQLite connection to the database to check.

    Returns:
        A :class:`ParityResult` with one :class:`Mismatch` per diverging cell
        and a ``cells_compared`` count.  An empty ``mismatches`` list with
        ``cells_compared > 0`` means the checked aggregates are consistent.
    """
    member = _member_scopes(conn)
    batting_mismatches, batting_cells = _check_table(
        conn,
        season_table="player_season_batting",
        recompute_sql=_BATTING_RECOMPUTE_SQL,
        recompute_keys=_BATTING_RECOMPUTE_KEYS,
        diff_columns=_BATTING_COLUMNS,
        source_scope_sql=_BATTING_SOURCE_SCOPE_SQL,
        member_scopes=member,
    )
    pitching_mismatches, pitching_cells = _check_table(
        conn,
        season_table="player_season_pitching",
        recompute_sql=_PITCHING_RECOMPUTE_SQL,
        recompute_keys=_PITCHING_RECOMPUTE_KEYS,
        diff_columns=_PITCHING_COLUMNS,
        source_scope_sql=_PITCHING_SOURCE_SCOPE_SQL,
        member_scopes=member,
    )
    return ParityResult(
        mismatches=batting_mismatches + pitching_mismatches,
        cells_compared=batting_cells + pitching_cells,
    )
