-- Purpose-built rollup-consistent fixture for the aggregate-parity guard
-- (E-234-02).  Used ONLY by tests/test_aggregate_parity.py.  NOT seed.sql.
--
-- Independent-oracle construction (testing.md "test validates spec"):
--   * Per-game rows below are the source data.
--   * Every stored player_season_* row is the EXACT perspective-filtered SUM
--     of this fixture's player_game_* rows, hand-computed independently of the
--     recompute code -- so the green-path test verifies the recompute query is
--     actually correct, not merely that two copies of the same SUM agree.
--   * A loader-built fixture was rejected on purpose: it would make the stored
--     side a near-copy of the recompute logic, passing by construction even if
--     that shared logic (gs CASE, perspective filter, a dropped column) were
--     wrong.
--
-- Epic C anchor: this static SQL fixture is the fixed anchor for the cutover
-- gate and must survive Epic C (ScoutingLoader/GameLoader refactors) untouched.
-- A guard for a loader refactor must be independent of loader internals.
--
-- Lock-step maintenance invariant (review-enforced): if the ScoutingLoader
-- aggregate CONTRACT changes (a SUM-subset column added/removed, or the gs
-- definition), update BOTH src/reports/aggregate_parity.py AND the expected
-- season values below in lock-step -- hand-recomputed from the game rows,
-- never regenerated by dumping loader output.
--
-- NOTE on two corrected values vs the E-234 epic Technical Notes TN-2:
--   TN-2's documented expected rollups contained two arithmetic slips relative
--   to TN-2's own documented game rows.  The game rows here are verbatim from
--   TN-2; the stored season rows use the true hand-computed SUMs:
--     * PB_02 bb: game rows sum to 1 (TN-2 expected said 2).
--     * PP_02 so: game rows sum to 9 (TN-2 expected said 8).
--   All other values match TN-2 exactly.  Per the lock-step invariant the game
--   rows are primary and the season values are their genuine sum.
--
-- Scaffolding: 1 team T, season 2026, 3 games PG_1/PG_2/PG_3,
--   batters PB_01/PB_02, pitchers PP_01/PP_02/PP_03.
--   Every IN-SCOPE game stat row: perspective_team_id = team_id = T.
--   Season rows leave stat_completeness unset (-> default 'boxscore_only') and
--   populate ONLY the diffed SUM-subset columns (no split / home-away columns)
--   -- faithfully modelling real ScoutingLoader boxscore_only output.
--   T uses gc_uuid 'TEAM_T' as a stable symbolic name for FK subqueries; OPP
--   (gc_uuid 'TEAM_OPP') is the home/away counter-party and also carries the
--   cross-team out-of-scope rows below.
--
-- FILTER-EXCLUSION PROOF (out-of-scope rows -- see the "Out-of-scope" section):
--   The recompute filters on team_id = T AND season_id = 2026 AND
--   perspective_team_id = T (mirrored in BOTH the batting and pitching queries
--   of src/reports/aggregate_parity.py).  With a single-scope fixture, a
--   recompute that silently DROPPED any one of those three filters would
--   produce byte-identical output and the green path would still pass -- the
--   exact wrong-scope regression this Epic C cutover gate must catch (the
--   perspective filter specifically guards the cross-perspective duplicate-stat
--   bug class -- see CLAUDE.md "Perspective provenance").  To make each filter
--   load-bearing, the fixture seeds rows that are EXCLUDED by exactly one
--   filter and would leak into the (T, 2026, persp=T) recompute if
--   that filter were removed -- breaking the empty-mismatch / cells_compared=74
--   assertions.  All such rows live OUTSIDE the diffed scope, so on the correct
--   recompute they change nothing.  Both batting and pitching get all three
--   (the two queries hold separate copies of the filter):
--     * cross-perspective: (PG_1, PB_01/PP_01, team=T, persp=OPP) -- excluded
--       by the perspective filter; leaks if it is dropped.
--     * cross-season: (OG_SEASON in 2025, PB_01/PP_01, team=T,
--       persp=T) -- excluded by the season filter; leaks if it is dropped.
--       (This scope is also made member-loaded -- see the MEMBER-LOADED section
--       -- so the missing-aggregate detection does not flag it on the green
--       path while it still probes the season filter.)
--     * cross-team: (PG_1, POPP_01, team=OPP, persp=T) -- excluded by the
--       team_id filter; leaks (as a new unstored player) if it is dropped.
--   Out-of-scope stat values are deliberately uniform sentinels (batting 9s,
--   pitching 99s) so any leak is obvious.  No stored player_season_* row exists
--   for OPP, POPP_01, or 2025 -- stored stays scoped to
--   T / 2026 so the green path is exact-empty.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Seasons (2026 is in-scope; 2025 carries the
-- cross-season out-of-scope rows)
-- ---------------------------------------------------------------------------
INSERT INTO seasons (season_id, name, season_type, year) VALUES
    ('2026', 'Spring 2026 High School', 'default', 2026),
    ('2025', 'Summer 2025 Legion',      'default', 2025);

-- ---------------------------------------------------------------------------
-- Teams (gc_uuid acts as a stable symbolic name for FK subquery lookups)
-- ---------------------------------------------------------------------------
INSERT INTO teams (name, membership_type, gc_uuid) VALUES
    ('Team T',        'tracked', 'TEAM_T'),
    ('Opponent Side', 'tracked', 'TEAM_OPP');

-- ---------------------------------------------------------------------------
-- Players
-- ---------------------------------------------------------------------------
INSERT INTO players (player_id, first_name, last_name) VALUES
    ('PB_01',   'Bat',   'One'),
    ('PB_02',   'Bat',   'Two'),
    ('PP_01',   'Pitch', 'One'),
    ('PP_02',   'Pitch', 'Two'),
    ('PP_03',   'Pitch', 'Three'),
    -- Belongs to OPP; only ever appears on cross-team out-of-scope rows.
    ('POPP_01', 'Opp',   'Player');

-- ---------------------------------------------------------------------------
-- Games (all 2026; T home, OPP away -- home/away irrelevant to the
-- recompute, which joins games only for season_id)
-- ---------------------------------------------------------------------------
INSERT INTO games (game_id, season_id, game_date, home_team_id, away_team_id, status) VALUES
    ('PG_1', '2026', '2026-03-10',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    ('PG_2', '2026', '2026-03-17',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    ('PG_3', '2026', '2026-03-24',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    -- Out-of-scope game in a SECOND season (cross-season exclusion proof).
    ('OG_SEASON', '2025', '2025-07-01',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed');

-- ---------------------------------------------------------------------------
-- Player game batting (cols: ab, r, h, doubles, triples, hr, rbi, bb, so, sb,
--   tb, hbp, shf, cs).  perspective_team_id = team_id = T.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_batting
    (game_id, player_id, team_id, perspective_team_id,
     ab, r, h, doubles, triples, hr, rbi, bb, so, sb, tb, hbp, shf, cs) VALUES
    -- PB_01
    ('PG_1', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 1, 2, 1, 0, 0, 1, 1, 1, 1, 3, 0, 0, 0),
    ('PG_2', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     3, 2, 1, 0, 0, 1, 2, 2, 0, 0, 4, 1, 1, 0),
    ('PG_3', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 0, 1, 0, 1, 0, 0, 0, 2, 1, 3, 0, 0, 1),
    -- PB_02
    ('PG_1', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0),
    ('PG_2', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     3, 1, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0),
    ('PG_3', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0);

-- ---------------------------------------------------------------------------
-- Player game pitching (cols: appearance_order, ip_outs, h, r, er, bb, so, wp,
--   hbp, pitches, total_strikes, bf).  perspective_team_id = team_id = T.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_pitching
    (game_id, player_id, team_id, perspective_team_id,
     appearance_order, ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf) VALUES
    -- PP_01 (start in PG_1, relief in PG_3): gs counts STARTS not appearances
    ('PG_1', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 18, 5, 3, 2, 2, 7, 1, 1, 85, 55, 24),
    ('PG_3', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     2, 6, 1, 0, 0, 0, 3, 0, 0, 28, 20, 7),
    -- PP_02 (two starts)
    ('PG_2', 'PP_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 21, 4, 1, 1, 1, 5, 0, 0, 92, 60, 26),
    ('PG_3', 'PP_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 15, 7, 4, 4, 3, 4, 2, 1, 78, 48, 23),
    -- PP_03 (gs-NULL branch: only appearance has NULL appearance_order)
    ('PG_1', 'PP_03', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     NULL, 12, 4, 2, 2, 1, 3, 0, 0, 50, 32, 15);

-- ---------------------------------------------------------------------------
-- OUT-OF-SCOPE rows (filter-exclusion proof -- see header).  Each is excluded
-- by exactly one of the three recompute filters and would leak into the
-- (T, 2026, persp=T) recompute if that filter were dropped, breaking
-- the empty-mismatch / cells_compared=74 assertions.  Sentinel values: batting
-- all-9s, pitching all-99s.  On the CORRECT recompute these change nothing.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_batting
    (game_id, player_id, team_id, perspective_team_id,
     ab, r, h, doubles, triples, hr, rbi, bb, so, sb, tb, hbp, shf, cs) VALUES
    -- cross-perspective: PB_01, team=T but persp=OPP (excluded by persp filter)
    ('PG_1', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9),
    -- cross-season: PB_01, team=T persp=T but game in 2025
    ('OG_SEASON', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9),
    -- cross-team: POPP_01, team=OPP but persp=T (excluded by team_id filter)
    ('PG_1', 'POPP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9);

INSERT INTO player_game_pitching
    (game_id, player_id, team_id, perspective_team_id,
     appearance_order, ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf) VALUES
    -- cross-perspective: PP_01, team=T but persp=OPP (excluded by persp filter)
    ('PG_1', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99),
    -- cross-season: PP_01, team=T persp=T but game in 2025
    ('OG_SEASON', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99),
    -- cross-team: POPP_01, team=OPP but persp=T (excluded by team_id filter)
    ('PG_1', 'POPP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99);

-- ---------------------------------------------------------------------------
-- Stored player_season_batting (gp = games_tracked = COUNT(*) = 3).
-- stat_completeness unset -> default 'boxscore_only'.  SUM-subset columns only.
--   PB_01: ab11 h4 doubles1 triples1 hr1 rbi3 r3 bb3 so3 sb2 tb10 hbp1 shf1 cs1
--   PB_02: ab11 h4 doubles1 triples0 hr0 rbi2 r2 bb1 so4 sb1 tb5  hbp1 shf0 cs0
--     (bb = 0+1+0 = 1; see corrected-value note in header)
-- ---------------------------------------------------------------------------
INSERT INTO player_season_batting
    (player_id, team_id, season_id, gp, games_tracked,
     ab, h, doubles, triples, hr, rbi, r, bb, so, sb, tb, hbp, shf, cs) VALUES
    ('PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2026', 3, 3,
     11, 4, 1, 1, 1, 3, 3, 3, 3, 2, 10, 1, 1, 1),
    ('PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2026', 3, 3,
     11, 4, 1, 0, 0, 2, 2, 1, 4, 1, 5, 1, 0, 0);

-- ---------------------------------------------------------------------------
-- Stored player_season_pitching (gp_pitcher = games_tracked = appearance count).
-- stat_completeness unset -> default 'boxscore_only'.  SUM-subset columns only.
--   PP_01: gp2 ip_outs24 h6 r3 er2 bb2 so10 wp1 hbp1 pitches113 ts75 bf31 gs=1
--          (games_tracked=2 but gs=1 -- gs counts STARTS, not appearances)
--   PP_02: gp2 ip_outs36 h11 r5 er5 bb4 so9 wp2 hbp1 pitches170 ts108 bf49 gs=2
--          (so = 5+4 = 9; see corrected-value note in header)
--   PP_03: gp1 ip_outs12 h4 r2 er2 bb1 so3 wp0 hbp0 pitches50 ts32 bf15 gs=NULL
--          (only appearance has NULL order -> MAX IS NULL -> gs NULL)
-- ---------------------------------------------------------------------------
INSERT INTO player_season_pitching
    (player_id, team_id, season_id, gp_pitcher, games_tracked,
     ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf, gs) VALUES
    ('PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2026', 2, 2,
     24, 6, 3, 2, 2, 10, 1, 1, 113, 75, 31, 1),
    ('PP_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2026', 2, 2,
     36, 11, 5, 5, 4, 9, 2, 1, 170, 108, 49, 2),
    ('PP_03', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2026', 1, 1,
     12, 4, 2, 2, 1, 3, 0, 0, 50, 32, 15, NULL);

-- ---------------------------------------------------------------------------
-- MEMBER-LOADED scope (T, 2025): false-positive guard (case b).
-- This scope has cross-season game rows (PB_01 / PP_01 in OG_SEASON, persp=T)
-- AND stored rows of completeness 'full' -- modelling a team loaded via the
-- member season-stats loader, whose season rows come straight from the API and
-- are NOT summed from games.  The gate must EXCLUDE it: it has stored rows of
-- some completeness (so it is not a "missing aggregate"), and zero
-- boxscore_only rows (so it is not a validated scope).  The stored values here
-- are deliberately NOT the SUM of the 9/99 game rows -- if the gate ever
-- wrongly checked this scope, those non-matching values would surface as a
-- false positive, which test_member_loaded_scope_not_flagged asserts does NOT
-- happen.  (This is ALSO why the cross-season exclusion rows need a home: with
-- the missing-aggregate detection added, an unstored perspective=team scope
-- would otherwise be flagged -- making it member-loaded keeps the green path
-- exact while still probing the recompute's season filter.)
-- ---------------------------------------------------------------------------
INSERT INTO player_season_batting
    (player_id, team_id, season_id, stat_completeness, gp, games_tracked,
     ab, h, doubles, triples, hr, rbi, r, bb, so, sb, tb, hbp, shf, cs) VALUES
    ('PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2025', 'full',
     7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7);

INSERT INTO player_season_pitching
    (player_id, team_id, season_id, stat_completeness, gp_pitcher, games_tracked,
     ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf, gs) VALUES
    ('PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), '2025', 'full',
     7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7);
