-- Purpose-built rollup-consistent fixture for the query-time season projection
-- (E-234-02, repurposed by E-259).  Used by tests/test_season_projection.py and
-- tests/test_season_query_cutover.py.  NOT seed.sql.
--
-- (Historically this fixture also seeded stored player_season_* rows as an
-- independent oracle for the aggregate-parity guard; E-259-03 dropped those
-- tables, so this fixture now seeds ONLY per-game rows and the expected season
-- line is hand-computed in the consuming tests' golden tuples.)
--
-- Independent-oracle construction (testing.md "test validates spec"):
--   * Per-game rows below are the source data.
--   * The expected season line is the EXACT perspective-filtered SUM of these
--     player_game_* rows, hand-computed independently of the projection code
--     (pinned in test_season_projection.py's _GOLDEN_* tuples) -- so the test
--     verifies the projection/reader query is actually correct, not merely that
--     two copies of the same SUM agree.
--   * A loader-built fixture was rejected on purpose: it would make the expected
--     side a near-copy of the projection logic, passing by construction even if
--     that shared logic (gs CASE, perspective filter, a dropped column) were
--     wrong.
--
-- Static-anchor fixture: hand-authored (not loader-built) so it stays a stable
-- independent oracle across loader refactors -- a guard for a loader refactor
-- must be independent of loader internals.
--
-- Lock-step maintenance invariant (review-enforced): if the shared SUM
-- projection CONTRACT changes (a SUM-subset column added/removed, or the gs
-- definition in src/db/season_aggregates.py), update the expected season values
-- in test_season_projection.py in lock-step -- hand-recomputed from the game
-- rows, never regenerated by dumping query output.
--
-- NOTE on two corrected values vs the E-234 epic Technical Notes TN-2:
--   TN-2's documented expected rollups contained two arithmetic slips relative
--   to TN-2's own documented game rows.  The game rows here are verbatim from
--   TN-2; the expected season values use the true hand-computed SUMs:
--     * PB_02 bb: game rows sum to 1 (TN-2 expected said 2).
--     * PP_02 so: game rows sum to 9 (TN-2 expected said 8).
--   All other values match TN-2 exactly.  Per the lock-step invariant the game
--   rows are primary and the season values are their genuine sum.
--
-- Scaffolding: 1 team T, season 2026, 3 games PG_1/PG_2/PG_3,
--   batters PB_01/PB_02, pitchers PP_01/PP_02/PP_03.
--   Every IN-SCOPE game stat row: perspective_team_id = team_id = T.
--   T uses gc_uuid 'TEAM_T' as a stable symbolic name for FK subqueries; OPP
--   (gc_uuid 'TEAM_OPP') is the home/away counter-party and also carries the
--   cross-team out-of-scope rows below.
--
-- FILTER-EXCLUSION PROOF (out-of-scope rows -- see the "Out-of-scope" section):
--   The query-time reader filters on team_id = T AND season_id = 2026 AND
--   perspective_team_id = T (applied in both the batting and pitching readers in
--   src/api/db.py, wrapping the shared projection).  With a single-scope fixture,
--   a reader that silently DROPPED any one of those three filters would
--   produce byte-identical output and the green path would still pass -- the
--   exact wrong-scope regression the query-time reader tests must catch (the
--   perspective filter specifically guards the cross-perspective duplicate-stat
--   bug class -- see CLAUDE.md "Perspective provenance").  To make each filter
--   load-bearing, the fixture seeds rows that are EXCLUDED by exactly one
--   filter and would leak into the (T, 2026, persp=T) query if that filter were
--   removed -- inflating the summed season line beyond the hand-computed
--   golden.  All such rows live OUTSIDE the scope, so on the correct query they
--   change nothing.  Both batting and pitching get all three (the two readers
--   hold separate copies of the filter):
--     * cross-perspective: (PG_1, PB_01/PP_01, team=T, persp=OPP) -- excluded
--       by the perspective filter; leaks if it is dropped.
--     * cross-season: (OG_SEASON in 2025, PB_01/PP_01, team=T,
--       persp=T) -- excluded by the season filter; leaks if it is dropped.
--     * cross-team: (PG_1, POPP_01, team=OPP, persp=T) -- excluded by the
--       team_id filter; leaks (as a new unstored player) if it is dropped.
--   Out-of-scope stat values are deliberately uniform sentinels (batting 9s,
--   pitching 99s) so any leak is obvious.  No stored player_season_* row exists
--   for OPP, POPP_01, or 2025 -- stored stays scoped to
--   T / 2026 so the green path is exact-empty.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Seasons (2026 is in-scope; 2025 carries the
-- cross-season out-of-scope rows)
-- ---------------------------------------------------------------------------
INSERT INTO seasons (season_id, name, year) VALUES
    ('2026', 'Spring 2026 High School', 2026),
    ('2025', 'Summer 2025 Legion',      2025);

-- ---------------------------------------------------------------------------
-- Teams (gc_uuid acts as a stable symbolic name for FK subquery lookups)
-- ---------------------------------------------------------------------------
INSERT INTO teams (name, membership_type, gc_uuid) VALUES
    ('Team T',        'tracked', 'TEAM_T'),
    ('Opponent Side', 'tracked', 'TEAM_OPP');

-- ---------------------------------------------------------------------------
-- Players
-- ---------------------------------------------------------------------------
INSERT INTO players (player_id, first_name, last_name) VALUES
    ('PB_01',   'Bat',   'One'),
    ('PB_02',   'Bat',   'Two'),
    ('PP_01',   'Pitch', 'One'),
    ('PP_02',   'Pitch', 'Two'),
    ('PP_03',   'Pitch', 'Three'),
    -- Belongs to OPP; only ever appears on cross-team out-of-scope rows.
    ('POPP_01', 'Opp',   'Player');

-- ---------------------------------------------------------------------------
-- Games (all 2026; T home, OPP away -- home/away irrelevant to the query,
-- which joins games only for season_id)
-- ---------------------------------------------------------------------------
INSERT INTO games (game_id, season_id, game_date, home_team_id, away_team_id, status) VALUES
    ('PG_1', '2026', '2026-03-10',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    ('PG_2', '2026', '2026-03-17',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    ('PG_3', '2026', '2026-03-24',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed'),
    -- Out-of-scope game in a SECOND season (cross-season exclusion proof).
    ('OG_SEASON', '2025', '2025-07-01',
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_T'),
     (SELECT id FROM teams WHERE gc_uuid = 'TEAM_OPP'), 'completed');

-- ---------------------------------------------------------------------------
-- Player game batting (cols: ab, r, h, doubles, triples, hr, rbi, bb, so, sb,
--   tb, hbp, shf, cs).  perspective_team_id = team_id = T.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_batting
    (game_id, player_id, team_id, perspective_team_id,
     ab, r, h, doubles, triples, hr, rbi, bb, so, sb, tb, hbp, shf, cs) VALUES
    -- PB_01
    ('PG_1', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 1, 2, 1, 0, 0, 1, 1, 1, 1, 3, 0, 0, 0),
    ('PG_2', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     3, 2, 1, 0, 0, 1, 2, 2, 0, 0, 4, 1, 1, 0),
    ('PG_3', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 0, 1, 0, 1, 0, 0, 0, 2, 1, 3, 0, 0, 1),
    -- PB_02
    ('PG_1', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0),
    ('PG_2', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     3, 1, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0),
    ('PG_3', 'PB_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     4, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0);

-- ---------------------------------------------------------------------------
-- Player game pitching (cols: appearance_order, ip_outs, h, r, er, bb, so, wp,
--   hbp, pitches, total_strikes, bf).  perspective_team_id = team_id = T.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_pitching
    (game_id, player_id, team_id, perspective_team_id,
     appearance_order, ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf) VALUES
    -- PP_01 (start in PG_1, relief in PG_3): gs counts STARTS not appearances
    ('PG_1', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 18, 5, 3, 2, 2, 7, 1, 1, 85, 55, 24),
    ('PG_3', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     2, 6, 1, 0, 0, 0, 3, 0, 0, 28, 20, 7),
    -- PP_02 (two starts)
    ('PG_2', 'PP_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 21, 4, 1, 1, 1, 5, 0, 0, 92, 60, 26),
    ('PG_3', 'PP_02', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 15, 7, 4, 4, 3, 4, 2, 1, 78, 48, 23),
    -- PP_03 (gs-NULL branch: only appearance has NULL appearance_order)
    ('PG_1', 'PP_03', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     NULL, 12, 4, 2, 2, 1, 3, 0, 0, 50, 32, 15);

-- ---------------------------------------------------------------------------
-- OUT-OF-SCOPE rows (filter-exclusion proof -- see header).  Each is excluded
-- by exactly one of the three reader filters and would leak into the
-- (T, 2026, persp=T) query if that filter were dropped, inflating the summed
-- season line beyond the golden.  Sentinel values: batting all-9s, pitching
-- all-99s.  On the CORRECT query these change nothing.
-- ---------------------------------------------------------------------------
INSERT INTO player_game_batting
    (game_id, player_id, team_id, perspective_team_id,
     ab, r, h, doubles, triples, hr, rbi, bb, so, sb, tb, hbp, shf, cs) VALUES
    -- cross-perspective: PB_01, team=T but persp=OPP (excluded by persp filter)
    ('PG_1', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9),
    -- cross-season: PB_01, team=T persp=T but game in 2025
    ('OG_SEASON', 'PB_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9),
    -- cross-team: POPP_01, team=OPP but persp=T (excluded by team_id filter)
    ('PG_1', 'POPP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9);

INSERT INTO player_game_pitching
    (game_id, player_id, team_id, perspective_team_id,
     appearance_order, ip_outs, h, r, er, bb, so, wp, hbp, pitches, total_strikes, bf) VALUES
    -- cross-perspective: PP_01, team=T but persp=OPP (excluded by persp filter)
    ('PG_1', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99),
    -- cross-season: PP_01, team=T persp=T but game in 2025
    ('OG_SEASON', 'PP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_T'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99),
    -- cross-team: POPP_01, team=OPP but persp=T (excluded by team_id filter)
    ('PG_1', 'POPP_01', (SELECT id FROM teams WHERE gc_uuid='TEAM_OPP'), (SELECT id FROM teams WHERE gc_uuid='TEAM_T'),
     1, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99);

-- ---------------------------------------------------------------------------
-- E-259-03 dropped player_season_batting / player_season_pitching, so this
-- fixture no longer seeds stored season rows. The per-game rows above (in-scope
-- + the cross-perspective / cross-season / cross-team out-of-scope rows) remain
-- the independent oracle: the query-time projection / readers SUM the in-scope
-- rows and the three filters (team / season / perspective) exclude the rest.
-- ---------------------------------------------------------------------------
